//////////////////////////////////////
//
// Graphics .H file for .N3D
// IGRAB-ed on Sat Oct 15 21:28:47 1994
//
//////////////////////////////////////

typedef enum {



		ENUMEND
	     } graphicnums;

//
// Data LUMPs
//

//
// Amount of each data item
//
#define NUMCHUNKS    360
#define NUMFONT      0
#define NUMFONTM     0
#define NUMPICS      0
#define NUMPICM      0
#define NUMSPRITES   0
#define NUMTILE8     0
#define NUMTILE8M    0
#define NUMTILE16    144
#define NUMTILE16M   216
#define NUMTILE32    0
#define NUMTILE32M   0
#define NUMEXTERNS   0
//
// File offsets for data items
//
#define STARTFONT    0
#define STARTFONTM   0
#define STARTPICS    0
#define STARTPICM    0
#define STARTSPRITES 0
#define STARTTILE8   0
#define STARTTILE8M  0
#define STARTTILE16  0
#define STARTTILE16M 144
#define STARTTILE32  360
#define STARTTILE32M 360
#define STARTEXTERNS 360

//
// Thank you for using IGRAB!
//
