///////////////////////////////////////
//
// TED5 Map Header for N3D
//
///////////////////////////////////////

//
// Map Names
//
typedef enum {
		NOAH_1-1_MAP,            // 0
		NOAH_1-2_MAP,            // 1
		NOAH_1-BOSS_MAP,         // 2
		NOAH_2-1_MAP,            // 3
		NOAH_2-2_MAP,            // 4
		NOAH_2-3_MAP,            // 5
		NOAH_2-BOSS_MAP,         // 6
		NOAH_3-1_MAP,            // 7
		NOAH_3-2_MAP,            // 8
		NOAH_3-3_MAP,            // 9
		NOAH_3-BOSS_MAP,         // 10
		NOAH_3-SECRET_MAP,       // 11
		NOAH_4-1_MAP,            // 12
		NOAH_4-2_MAP,            // 13
		NOAH_4-3_MAP,            // 14
		NOAH_4-4_MAP,            // 15
		NOAH_4-BOSS_MAP,         // 16
		NOAH_5-1_MAP,            // 17
		NOAH_5-2_MAP,            // 18
		NOAH_5-3_MAP,            // 19
		NOAH_5-4_MAP,            // 20
		NOAH_5-5_MAP,            // 21
		NOAH_5-BOSS_MAP,         // 22
		NOAH_6-1_MAP,            // 23
		NOAH_6-2_MAP,            // 24
		NOAH_6-3_MAP,            // 25
		NOAH_6-4_MAP,            // 26
		NOAH_6-5_MAP,            // 27
		NOAH_6-BOSS_MAP,         // 28
		NOAH_6-SECRET_MAP,       // 29
		NOAH_CAST_MAP,           // 30
		LASTMAP
	     } mapnames;
