// generated by sprgrab

typedef struct { unsigned short width, firstcol;} sprite_t;

sprite_t	sprites[] = {
{51,0},
{53,51},
{51,104},
{53,155},
{48,208},
{49,256},
{51,305},
{50,356}
};
