#include <stdio.h>
#include <string.h>
#include <alloc.h>
#include <dir.h>
#include <dos.h>
#include <mem.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <io.h>
#include <process.h>
#include <bios.h>
#include <stdarg.h>
#include <ctype.h>
#include <stdlib.h>

#include "types.h"
#include "minmisc.h"
#include "script.h"




long ParseHex (char *hex)
{
	char	*str;
	long	num;

	num = 0;
	str = hex;

	while (*str)
	{
		num <<= 4;
		if (*str >= '0' && *str <= '9')
			num += *str-'0';
		else if (*str >= 'a' && *str <= 'f')
			num += 10 + *str-'a';
		else if (*str >= 'A' && *str <= 'F')
			num += 10 + *str-'A';
		else
			MS_Quit ("Bad hex number: %s",hex);
		str++;
	}

    return num;
}


long ParseNum (char *str)
{
	if (str[0] == '$')
		return ParseHex (str+1);
	if (str[0] == '0' && str[1] == 'x')
		return ParseHex (str+2);
	return atol (str);
}


/*
=============================================================================

							MAIN

=============================================================================
*/


/*
=================
=
= main
=
=================
*/

void main(int argc, char **argv)
{
	int			i;
	long		size,offset;
	int			hcols;
	int			collumns,sprites;
	long		datapos, newpos, org, length, align;
	char		name[80];
	FILE		*header, *cheader;
	int			datahandle, srchandle;
	char		far *buffer;
	unsigned	count, skip;

	if (argc != 2)
		MS_Quit ("romlink namebase(.rl/.rom/.s/.h)");

	buffer = SafeMalloc (0xf000);

//
// read in the script file
//
	strcpy (name,argv[1]);
	strcat (name,".rl");
	LoadScriptFile (name);

	strcpy (name,argv[1]);
	strcat (name,".rom");
	datahandle = SafeOpenWrite (name);
	datapos = 0;

	strcpy (name,argv[1]);
	strcat (name,".s");
	header = fopen (name,"w");
	if (!header)
		MS_Quit ("Couldn't open %s : %s",name,strerror(errno));

	fprintf (header," case on\r\rrdummy DATA\r END\r\rromlink DATA\r\r");

	strcpy (name,argv[1]);
	strcat (name,".h");
	cheader = fopen (name,"w");
	if (!cheader)
		MS_Quit ("Couldn't open %s : %s",name,strerror(errno));

	fprintf (cheader,"/* generated by romlink */\r\r");

//
// parse script
//
// first line $org c20000
//
// diskfile label [nocross]
	GetToken (true);
	if (strcmp (token,"$org"))
		MS_Quit ("First command is not $org");
	GetToken (false);
	org = ParseNum (token);

	while (1)
	{
		printf ("0x%6lx ", datapos);
		GetToken (true);
		if (endofscript)
			break;

		if (!strcmp (token,"$align") )
		{
			GetToken (false);
			align = ParseNum (token);
			newpos = (datapos + align -1) & ~(align-1);
			if (newpos != datapos)
			{
				lseek (datahandle, newpos-datapos, SEEK_END);
				datapos = newpos;
			}
			printf ("$ALIGN %lu\n",align);
			continue;
		}

		srchandle = SafeOpenRead (token);
		length = filelength (srchandle);

//
// get label name
//
		GetToken (true);
		strcpy (name, token);

//
// check for bank crossing
//
		if (TokenAvailable ())
		{
			// don't let it cross a bank boundary
			if (length > 0x10000l)
				MS_Quit ("Can't keep a >64k file from crossing a bank");
			if ( (datapos+length-1)>>16 != datapos>>16 )
			{
				printf ("$NOCROSS\n");
				skip = 0x10000l - (datapos&0xffff);
				datapos += skip;
				lseek (datahandle, skip, SEEK_END);
				printf ("0x%6lx ", datapos);
			}
			GetToken (true);
		}

		printf ("%s\n", name);
		fprintf (header,"%s gequ $%lx\r", name, datapos+org);
		fprintf (cheader,"extern char %s;\r", name);

//
// copy file
//
		datapos += length;
		while (length)
		{
			count = length > 0xf000 ? 0xf000 : length;
			SafeRead (srchandle, buffer, count);
			SafeWrite (datahandle, buffer, count);
			length -= count;
		}

		close (srchandle);

	}

//
// end files
//
	fprintf (header,"\r\r END\r");
	fclose (header);

	fprintf (cheader,"\r");
	fclose (cheader);

	close (datahandle);

	exit (0);
}


