#define VERSION	"v0.5"

/*
=============================================================================

							  SNESGRAB

						  by John Carmack

=============================================================================
*/


#include <stdio.h>
#include <string.h>
#include <alloc.h>
#include <dir.h>
#include <dos.h>
#include <mem.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <io.h>
#include <process.h>
#include <bios.h>
#include <stdarg.h>
#include <ctype.h>
#include <stdlib.h>

#include "cmdlib.h"
#include "scriplib.h"
#include "lbmlib.h"

#define SCREENWIDTH		320
#define SCREENHEIGHT	200

#define PEL_WRITE_ADR		0x3c8
#define PEL_READ_ADR		0x3c7
#define PEL_DATA			0x3c9



byte	*tilebuffer, *buf_p;

int			datahandle;
unsigned	iocount;

int		tiles;

FILE		*ftiles = NULL;

/*
=============================================================================

							GRABBING

=============================================================================
*/

#define SCRN(x,y)	(*(byte *)MK_FP(0xa000,(y)*SCREENWIDTH+(x)))


/*
=================
=
= GrabPalette
=
=================
*/

void GrabPalette (void)
{
	int	i, r, g, b;

	outp (PEL_READ_ADR,0);
	for (i=0 ; i<256 ; i++)
	{
		r = inp (PEL_DATA) >>1;
		g = inp (PEL_DATA) >>1;
		b = inp (PEL_DATA) >>1;
		*((short *)buf_p)++ = (b<<10) + (g<<5) + r;
	}

}


/*
=================
=
= GrabDimPalette
=
= Dim the middle 256-32 colors
=================
*/

void GrabDimPalette (void)
{
	int	i, r, g, b;

	outp (PEL_READ_ADR,0);
	for (i=0 ; i<16 ; i++)
	{
		r = inp (PEL_DATA) >>1;
		g = inp (PEL_DATA) >>1;
		b = inp (PEL_DATA) >>1;
		*((short *)buf_p)++ = (b<<10) + (g<<5) + r;
	}
	for ( ; i<240 ; i++)
	{
		r = inp (PEL_DATA) >>2;
		g = inp (PEL_DATA) >>2;
		b = inp (PEL_DATA) >>2;
		*((short *)buf_p)++ = (b<<10) + (g<<5) + r;
	}
	for ( ; i<256 ; i++)
	{
		r = inp (PEL_DATA) >>1;
		g = inp (PEL_DATA) >>1;
		b = inp (PEL_DATA) >>1;
		*((short *)buf_p)++ = (b<<10) + (g<<5) + r;
	}
}


/*
=================
=
= GrabTile
=
= x/y are tile coordinates (pixels*8)
=================
*/

void GrabTile (int x, int y, int planes)
{
	int	sx,sy;
	byte	tile[8][8], b;

//
// grab it
//
	for (sy = 0 ; sy< 8 ; sy++)
		for (sx = 0 ; sx< 8 ; sx++)
		{
			tile[sy][sx] = SCRN(x*8+sx,y*8+sy);
			SCRN(x*8+sx,y*8+sy) = 0xff;
		}

	if (planes == 7)
	{	// mode 7 tiles are just bytes
		memcpy (buf_p, tile, 64);
		buf_p += 64;
		tiles ++;
		return;
	}

//
// munge it
//
	memset (buf_p,0,64);

	for (sy = 0 ; sy< 8 ; sy++)
		for (sx = 0 ; sx< 8 ; sx++)
		{
			b = tile[sy][sx];

			buf_p[sy*2] <<=1;
			buf_p[sy*2] |= b&1;
			b>>=1;

			buf_p[sy*2+1] <<=1;
			buf_p[sy*2+1] |= b&1;
			b>>=1;

			if (planes == 2)
				continue;

			buf_p[1*16+sy*2] <<=1;
			buf_p[1*16+sy*2] |= b&1;
			b>>=1;

			buf_p[1*16+sy*2+1] <<=1;
			buf_p[1*16+sy*2+1] |= b&1;
			b>>=1;

			if (planes == 4)
				continue;

			buf_p[2*16+sy*2] <<=1;
			buf_p[2*16+sy*2] |= b&1;
			b>>=1;

			buf_p[2*16+sy*2+1] <<=1;
			buf_p[2*16+sy*2+1] |= b&1;
			b>>=1;

			buf_p[3*16+sy*2] <<=1;
			buf_p[3*16+sy*2] |= b&1;
			b>>=1;

			buf_p[3*16+sy*2+1] <<=1;
			buf_p[3*16+sy*2+1] |= b&1;
			b>>=1;
		}


	buf_p += 8*planes;
	tiles ++;
}


/*
=================
=
= GrabPic
=
$pic	-/<name>	planes x y w h
=================
*/

void GrabPic (void)
{
	int	x,y,w,h, planes;
	int	xs,ys, start;
	char	name[20], filename[80];

	GetToken (false);
	strcpy (name, token);


	GetToken (false);
	planes = atoi (token);
	GetToken (false);
	x = atoi (token);
	GetToken (false);
	y = atoi (token);
	GetToken (false);
	w = atoi (token);
	GetToken (false);
	h = atoi (token);

	start = tiles;

	for (ys = y ; ys<y+h ; ys++)
		for (xs = x ; xs<x+w ; xs++)
			GrabTile (xs,ys, planes);

//
// write header if name isn't '-'
//
	if ( !strcmp (name,"-") )
		return;

	if (!ftiles)
	{
		strcpy (filename,_argv[1]);
		strcat (filename,".h");
		ftiles = fopen (filename,"w");
		fprintf (ftiles,"/* generated by snesgrab */\r\r");
	}

	fprintf (ftiles, "#define %s_START\t\t%i\r",name,start);
	fprintf (ftiles, "#define %s_W\t\t%i\r",name,w);
	fprintf (ftiles, "#define %s_H\t\t%i\r",name,h);

}


/*
=================
=
= GrabRaw
=
= Raw linear byte block
$raw	x y w h (pixel based values)
=================
*/

void GrabRaw (void)
{
	int	x,y,w,h, planes;
	int	xs,ys, start;
	byte	*scrn;

	GetToken (false);
	x = atoi (token);
	GetToken (false);
	y = atoi (token);
	GetToken (false);
	w = atoi (token);
	GetToken (false);
	h = atoi (token);

	scrn = (byte *)MK_FP(0xa000,(y)*SCREENWIDTH+(x));

	for (ys = y ; ys<y+h ; ys++)
	{
		memcpy (buf_p,scrn,w);
		memset (scrn,0xff,w);
		scrn += SCREENWIDTH;
		buf_p += w;
	}
}


/*
=============================================================================

							MAIN

=============================================================================
*/

byte	nulpal[768];

/*
=================
=
= main
=
=================
*/

void main(int argc, char **argv)
{
	int			i;
	long		size,offset;
	int			hcols;
	int			collumns,sprites;
	long		datapos;
	char		name[80];
	byte		*picture, *palette;
	boolean		pause, loaded;

	pause = CheckParm("p");
	if (pause)
		argc--;

	if (argc != 2)
		Error ("snesgrab tileset [/p]");

	buf_p = tilebuffer = SafeMalloc (0x10000l);
	loaded = false;
	tiles = 0;

//
// read in the script file
//
	strcpy (name,argv[1]);
	strcat (name,".ss");
	LoadScriptFile (name);
	VGAMode ();


//
// parse script
//
	while (1)
	{
		GetToken (true);
		if (endofscript)
			break;

		if (!strcmp (token,"$load"))
		{
			if (pause && loaded)
				bioskey (0);
			loaded = true;

			GetToken (false);
			LoadLBM (token, &picture, &palette);
			SetPalette (nulpal);
			memcpy ((void *)0xa0000000l, picture, 64000);
			SetPalette (palette);
			free (palette);
			free (picture);
			continue;
		}

		if (!strcmp (token,"$palette"))
		{
			GrabPalette ();
			continue;
		}

		if (!strcmp (token,"$dimpalette"))
		{
			GrabDimPalette ();
			continue;
		}

		if (!strcmp (token,"$pic"))
		{
			GrabPic ();
			continue;
		}

		if (!strcmp (token,"$raw"))
		{
			GrabRaw ();
			continue;
		}

		if (!strcmp (token,"$save"))
		{
			GetToken (false);
			datahandle = SafeOpenWrite (token);
			SafeWrite (datahandle, tilebuffer, buf_p - tilebuffer);
			close (datahandle);
			buf_p = tilebuffer;
			tiles = 0;
			continue;
		}

		Error ("Unknown token %s",token);
	}

//
// end files
//
	fclose (ftiles);


//
// all done
//
	if (pause && loaded)
		bioskey (0);
	TextMode ();
	exit (0);
}


