//-------------------------------------------------------------------
// SNDLINK.C
//-------------------------------------------------------------------

#include	<stdio.h>
#include <stdlib.h>
#include	<string.h>
#include	<io.h>

#include "cmdlib.h"
#include "scriplib.h"

#define	MAXSAMPLES	64
unsigned	short fileorg[MAXSAMPLES][2];

unsigned	sharedofs[MAXSAMPLES];
unsigned	sharedlen[MAXSAMPLES];


//-------------------------------------------------------------------
// main(void)
//
// Sound RAM:	$0200	Driver program
//					$0600	64 entry sample table (ushort start, ushort loop)
//					$0700+	Sample data
//
// Generates:	SOUNDS.BIN		Contains the driver and all static samples
//					SHSOUNDS.BIN	Contains all the space shared samples
//					SOUNDS.H			Contains the sample numbers
//					SOUNDS.C			Contains the offset/lengths of shared sounds
//										  and start of shared area in sound RAM
//------------------------------------------------------------------

void main (void)
{
	int		i, fx, handle, shnum, loop;
	int		staticfile, sharedfile;
	long		org, length;
	int		overload, maxoversize;
	FILE		*header;
	unsigned	short vals[2], u;
	unsigned	sharedsize;
	void		*buffer;
	char		name[256];
	char		*zerobuf[16];

	printf ("Sndlink (v0.1) by John Carmack\n\n");

	LoadScriptFile ("sndlink.txt");

	header = fopen ("sounds.h","w");
	fprintf (header,"// Generated by SNDLINK.EXE\n\n");
	fprintf (header,"enum {\n");

	staticfile = SafeOpenWrite ("sounds.bin");

//-------------------------------
// Leave space for &header
//-------------------------------

	lseek (staticfile,4,SEEK_CUR);

//-------------------------------
// Copy the driver
//-------------------------------

	length = LoadFile ("driver",&buffer);
	SafeWrite (staticfile, buffer, length);
	free (buffer);

//-------------------------------
// Leave space for sample table
//   (64 samples*4)
//-------------------------------

	lseek (staticfile,0x504,SEEK_SET); // Samples start at RAM org 0x900

	fx = 0;
	org = 0x700;
	memset (zerobuf, 0, sizeof (zerobuf));
	
//-------------------------------
// Copy instruments
//-------------------------------

	while (1)
	{
		GetToken (true);	// Get sound name
		if (endofscript)
			break;

		if (!strcmpi(token,"$static"))
			break;

		strcpy (name, token);
		strcat (name,".sol");
		strupr (token);
		fprintf (header,"\t%s,\t\t// %d\n",token,fx);
		length = LoadFile (name,&buffer);
		length -= 0x40;	// Don't need header
		loop = *(unsigned int *)((byte *)buffer+4);
		loop = 9*(loop/16);
		SafeWrite (staticfile, (byte *)buffer + 0x40, length);
		fileorg[fx][0] = org;
		fileorg[fx][1] = org + loop;
		printf (" $%04X / $%04X %s\n",(unsigned)fileorg[fx][0],(unsigned)fileorg[fx][1],token);
		org += length;
		free (buffer);
		fx++;
	}

//-------------------------------
// Copy static sounds
//-------------------------------

	while (1)
	{
		GetToken (true);	// Get sound name
		if (endofscript)
			break;

		if (!strcmpi(token,"$shared"))
			break;

		strcpy (name, token);

		if (name[strlen(name)-1] == '-')
		{
			name[strlen(name)-1] = '\0';
			GetToken (false);
			loop = ParseNum (token);
			loop = 9*(loop/16);	// Adjust for SNDCODE filtering!
			printf (" $%04X\t%s\t(loop = $%04X)\n",(unsigned)org,name,(unsigned)loop);
		}
		else
		{
			loop = 0;
			printf (" $%04X\t%s\n",(unsigned)org,name);
		}

		if (!strcmp(name+strlen(name)-4,".sol") )
		{	// Instrument file
		
		}
		strcpy (token,name);
		strupr (token);
		strcat (name,".sns");
		fprintf (header,"\t%s,\t\t// %d\n",token,fx);
		length = LoadFile (name,&buffer);

#if 0
		if (loop) {
			char c0 = 0x02, c1 = 0x7A;

			if (loop > length)
			{
				printf ("\x07""Error: LOOP > LENGTH!\n");
				exit (1);
			}

			SafeWrite (staticfile, (void *) &c0, 1);
			SafeWrite (staticfile, zerobuf, 8);
			SafeWrite (staticfile, buffer, loop);
			SafeWrite (staticfile, (void *) &c1, 1);
			SafeWrite (staticfile, (void *) (((char *) buffer)+loop), length-loop);
			length += 2+8;
			loop += 1+8;
		} else
#endif

#if 0
		if (loop) {
//			SafeWrite (staticfile, zerobuf, 16);
			memset ((char *) buffer+loop, 0, 16);
			SafeWrite (staticfile, buffer, length);
			SafeWrite (staticfile, zerobuf, 16);
			length += 16;
//			loop += 16;
		} else
#endif

			SafeWrite (staticfile, buffer, length);

		fileorg[fx][0] = org;
		fileorg[fx][1] = org + loop;
		org += length;
		free (buffer);
		fx++;
	}

//-------------------------------
// Write the upload information
// for the shared file
//-------------------------------

	for (i = fx ; i<MAXSAMPLES ; i++)
		fileorg[i][0] = fileorg[i][1] = org;	// All the rest share space

	vals[0] = 0;				// Total length
	vals[1] = 0x200;			// Execution start address
	SafeWrite (staticfile,vals,4);

	lseek (staticfile,0,SEEK_SET);
	vals[0] = org - 0x200;	// Total length
	vals[1] = 0x200;			// Org in sound RAM
	SafeWrite (staticfile,vals,4);

	lseek (staticfile,0x404,SEEK_SET);
	SafeWrite (staticfile,fileorg,sizeof(fileorg));

	close (staticfile);

	sharedsize = 0xFFC0 - org;		// No shared sounds can be larger
	printf (" $%04lX\tEnd of STATIC data ($%04X bytes for shared)\n\n",org,sharedsize);
	if (org > 0xFFC0)
		Error ("ERROR: Static data too large");

//-------------------------------
// Build the shared sample file
//-------------------------------

	sharedfile = SafeOpenWrite ("shsounds.bin");
	org = 0;
	shnum = 0;

	while (1)
	{
		GetToken (true);		// Get sound name
		if (endofscript)
			break;

		printf (" $%04X\t%s\n",(unsigned)org,token);
		strcpy (name, token);
		strcat (name,".sns");
		length = LoadFile (name,&buffer);
		if (length > sharedsize)
			Error ("ERROR: Sample larger than shared space");
		strupr (token);
		fprintf (header,"\t%s,\t\t// %d\n",token,fx+shnum);
		sharedofs[shnum] = org;
		sharedlen[shnum] = (length+2)/3;
		SafeWrite (sharedfile,buffer, length);
		org+=length;
		free (buffer);
		shnum++;
	}

	printf (" $%04X\tEnd of SHARED data\n",org);
	close (sharedfile);


	fprintf (header,"NUMSOUNDS };\n\n");
	fprintf (header,"#define\tSHAREDSTART\t%i\n",fx);
	fprintf (header,"#define\tSHAREDORG\t0x%X\n",fileorg[fx][0]);
	fclose (header);

//-------------------------------
// Write the shared sound
// directory file
//-------------------------------

	header = fopen ("sounds.c","w");
	fprintf (header,"// Generated by SNDLINK.EXE\n\n");
	fprintf (header,"unsigned sharedofs[] = {\n");
	for (i=0 ; i<shnum ; i++)
		fprintf (header,"0x%X,\n",sharedofs[i]);
	fprintf (header,"0};\n\n");

	fprintf (header,"unsigned sharedlen[] = {\n");
	for (i=0 ; i<shnum ; i++)
		fprintf (header,"0x%X,\n",sharedlen[i]);
	fprintf (header,"0};\n\n");
}



