REM sndcode goddbd
REM sndcode goodsne
REM sndcode chihat
REM sndcode org
REM sndcode oboe
REM sndcode panflte
REM sndcode trnpt
REM sndcode hbass

sndcode d_antlpe
sndcode d_bear
sndcode d_bonus
sndcode d_camel
sndcode d_cochit
sndcode d_cocthr
sndcode d_dbite
sndcode d_edie
sndcode d_elphnt
sndcode d_extra
sndcode d_gatlin
sndcode d_girafe
sndcode d_goat
sndcode d_gunsht
sndcode d_kangro
sndcode d_knife
sndcode d_monkey
sndcode d_mstep
sndcode d_opendr
sndcode d_ostrch
sndcode d_ox
sndcode d_pain
sndcode d_pdie
sndcode d_pwall
sndcode d_sheep
sndcode d_wathit
sndcode d_watthr
sndcode d_spit

sndcode d_eat
sndcode d_closdr
sndcode d_inc
sndcode	d_key
sndcode d_push
sndcode	d_sling2

