#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define ANGLES  128

#define PI	3.141592657
#define	SLOPERANGE	512

void main (void)
{
	unsigned	i;
	float		angle;
	FILE		*f;
	int			v;

	f = fopen ("tables.c","w");
	if (!f)
	{
		printf ("couldn't open tables.c\n");
		exit (1);
	}

	fprintf (f,"/* generated by tablegen */\r\n#include \"wolfdef.h\"\r\n\r");


//
// sintable
//
	fprintf (f,"fixed_t sintable[ANGLES] = {\r");
	for (i=0 ; i<ANGLES ; i++)
	{
		angle = PI*2*(i+0.5)/ANGLES;
		v = sin (angle) * 0x100;
		fprintf (f,"%i",v);
		if (i != ANGLES-1)
			fprintf (f,",");
		if ( (i&15) == 15)
			fprintf (f,"\r");
	}
	fprintf (f,"};\r\r");



//
// costable
//
	fprintf (f,"fixed_t costable[ANGLES] = {\r");
	for (i=0 ; i<ANGLES ; i++)
	{
		angle = PI*2*(i+0.5)/ANGLES;
		v = cos (angle) * 0x100;
		fprintf (f,"%i",v);
		if (i != ANGLES-1)
			fprintf (f,",");
		if ( (i&15) == 15)
			fprintf (f,"\r");
	}
	fprintf (f,"};\r\r");


//
// tantoangle
//
	fprintf (f,"ushort tantoangle[513] = {\r");

	for (i=0 ; i<=SLOPERANGE ; i++)
	{
		angle = atan( (float)i/SLOPERANGE )/(PI*2);
		v = 0x10000l*angle;
		fprintf (f,"%i",v);
		if (i != SLOPERANGE)
			fprintf (f,",");
		if ( (i&15) == 15)
			fprintf (f,"\r");
	}
	fprintf (f,"};\r\r");


	fclose (f);

	printf ("done.\n");
}
